set_water_meter_calibration:
  fields:
    device_id:
      example: "d88b4c01000d987c"
      required: true
      selector:
        text:
    gallons:
      example: 12.5
      required: true
      selector:
        number:
          min: 0
          mode: box
    scale:
      required: false
      default: 0.001
      selector:
        number:
          min: 0
          step: 0.0001
          mode: box
    unit:
      required: false
      selector:
        select:
          options:
            - "gal"
            - "CCF"
            - "m³"
            - "L"