set_water_meter_calibration:
  fields:
    device_id:
      example: "d88b4c01000d987c"
      required: true
      selector:
        text:
    gallons:
      example: 12.5
      required: true
      selector:
        number:
          min: 0
          max: 1000000
          step: 0.001
    scale:
      example: 0.001
      required: false
      default: 0.001
      selector:
        number:
          min: 0.000001
          max: 100
          step: 0.000001
